import type { AuditEntry, Organization } from "./types";

const iso = (y: number, m: number, d: number, h = 23, min = 59) =>
  new Date(y, m - 1, d, h, min).toISOString();

export const CURRENT_ACTOR = "Павел Яхимович";

export const INITIAL_ORGS: Organization[] = [
  {
    id: "org_sirius",
    name: "Сириус",
    slug: "/sirius",
    ownerEmail: "pavel.yahimovich@gmail.com",
    status: "active",
    records: 2,
    seats: 3,
    createdAt: iso(2026, 6, 2, 10, 15),
    subscription: {
      status: "past_due",
      plan: "pilot",
      currentPeriodStart: iso(2026, 8, 15, 0, 1),
      currentPeriodEnd: iso(2026, 9, 15),
      accessOverrideUntil: null,
      overrideReason: null,
    },
  },
  {
    id: "org_test_1",
    name: "Тест",
    slug: "/test",
    ownerEmail: "bagan83858@jobscai.com",
    status: "active",
    records: 0,
    seats: 1,
    createdAt: iso(2026, 9, 9, 12, 0),
    subscription: {
      status: "trialing",
      plan: "pilot",
      currentPeriodStart: iso(2026, 9, 9, 0, 1),
      currentPeriodEnd: iso(2026, 9, 23),
      accessOverrideUntil: null,
      overrideReason: null,
    },
  },
  {
    id: "org_test_2",
    name: "Тест",
    slug: "/finb",
    ownerEmail: "belpolygran@gmail.com",
    status: "active",
    records: 0,
    seats: 2,
    createdAt: iso(2026, 9, 1, 9, 30),
    subscription: {
      status: "trialing",
      plan: "pilot",
      currentPeriodStart: iso(2026, 9, 1, 0, 1),
      currentPeriodEnd: iso(2026, 9, 15),
      accessOverrideUntil: null,
      overrideReason: null,
    },
  },
  {
    id: "org_nordwell",
    name: "Nordwell Clinic",
    slug: "/nordwell",
    ownerEmail: "admin@nordwell.by",
    status: "active",
    records: 1842,
    seats: 14,
    createdAt: iso(2026, 2, 11, 11, 0),
    subscription: {
      status: "active",
      plan: "business",
      currentPeriodStart: iso(2026, 9, 1, 0, 1),
      currentPeriodEnd: iso(2026, 10, 1),
      accessOverrideUntil: null,
      overrideReason: null,
    },
  },
  {
    id: "org_atelier",
    name: "Atelier Vera",
    slug: "/atelier-vera",
    ownerEmail: "vera@atelier.studio",
    status: "active",
    records: 431,
    seats: 6,
    createdAt: iso(2026, 4, 20, 14, 45),
    subscription: {
      status: "past_due",
      plan: "team",
      currentPeriodStart: iso(2026, 8, 5, 0, 1),
      currentPeriodEnd: iso(2026, 9, 5),
      accessOverrideUntil: iso(2026, 9, 22),
      overrideReason: "7 дней goodwill — разбираемся с платежом",
    },
  },
  {
    id: "org_kraft",
    name: "Kraft Auto",
    slug: "/kraft-auto",
    ownerEmail: "office@kraftauto.ru",
    status: "suspended",
    records: 908,
    seats: 9,
    createdAt: iso(2025, 12, 3, 8, 20),
    subscription: {
      status: "active",
      plan: "team",
      currentPeriodStart: iso(2026, 9, 3, 0, 1),
      currentPeriodEnd: iso(2026, 10, 3),
      accessOverrideUntil: null,
      overrideReason: null,
    },
  },
  {
    id: "org_lumen",
    name: "Lumen Legal",
    slug: "/lumen",
    ownerEmail: "hello@lumen.legal",
    status: "closed",
    records: 76,
    seats: 2,
    createdAt: iso(2025, 10, 18, 16, 0),
    subscription: {
      status: "canceled",
      plan: "team",
      currentPeriodStart: iso(2026, 7, 18, 0, 1),
      currentPeriodEnd: iso(2026, 8, 18),
      accessOverrideUntil: null,
      overrideReason: null,
    },
  },
];

export const INITIAL_AUDIT: AuditEntry[] = [
  {
    id: "a1",
    actor: "Система",
    organizationId: "org_sirius",
    action: "subscription_status_changed",
    field: "subscription.status",
    oldValue: "trialing",
    newValue: "past_due",
    reason: "Пробный период закончился, оплата не поступила",
    createdAt: iso(2026, 9, 16, 0, 5),
    source: "system",
  },
  {
    id: "a2",
    actor: CURRENT_ACTOR,
    organizationId: "org_atelier",
    action: "access_override_granted",
    field: "subscription.access_override_until",
    oldValue: "—",
    newValue: "22.09.2026",
    reason: "7 дней goodwill — разбираемся с платежом",
    createdAt: iso(2026, 9, 15, 10, 42),
    source: "saas_admin",
  },
  {
    id: "a3",
    actor: CURRENT_ACTOR,
    organizationId: "org_kraft",
    action: "organization_status_changed",
    field: "organization.status",
    oldValue: "active",
    newValue: "suspended",
    reason: "Жалоба на рассылку, аккаунт на проверке",
    createdAt: iso(2026, 9, 12, 15, 20),
    source: "saas_admin",
  },
  {
    id: "a4",
    actor: "Биллинг",
    organizationId: "org_nordwell",
    action: "payment_recorded",
    field: "subscription.current_period_end",
    oldValue: "01.09.2026",
    newValue: "01.10.2026",
    reason: "Автоплатёж по карте *4417",
    createdAt: iso(2026, 9, 1, 3, 12),
    source: "billing_webhook",
  },
];
